### ISSUE TITLE
BRouter gone from Google Play

### ISSUE THREAD

**Issue by andrixnet** [abrensch/brouter#139]
I've been successfully using BRouter with c:geo for geocaching. An excellent combo. 

Recently I switched phones and wanted to reinstall my apps, but BRouter wasn't to be found on the Google Play. I checked the older phone to make sure it's not an Android version issue or smth, but the older phone Play app also said "not found".

On the web: https://play.google.com/store/apps/details?id=btools.routingapp says 
"We're sorry, the requested URL was not found on this server."

A search for "brouter" yields no relevant result.

**Comment by poutnikl** [comment]
It may be unrelated, but Google announced in advance they would expel from the store applications that do not honour their new policy with respect some application permissions.

But as far as I know, it is about reading text messages and call logs.

Not sure if limited only to this.

**Comment by abrensch** [comment]
Thanx for the info. I checked in plays developer console: they say I violated the "Metadata policy" by mentioning "other brands like OsmAnd" in the app description. I updated the next now and resubmitted. However, chances are that this will fail again because I now viaote another policy that any newly updated map must be build against the Android API level 26 or higher... I will post here again if the app is availabe again on Play.

**Comment by Mincol** [comment]
It seems it is back. :)

**Comment by utack** [comment]
It is continuing, if you do upgrade to a new api version maybe you should directly go to 28, because it will be required later this year
https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html

**Comment by abrensch** [comment]
> It is continuing, if you do upgrade to a new api version maybe you should directly go to 28, because it will be required later this year
> https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html

When preparing a new release (see http://brouter.de/brouter/revisions.html ) I tried to also update to target api 28 

The resulting APK works without problems on Android 5, but mnot at all on Android 6.

It seems that api 28 requires you to do some extra tricks for every file access on any sd-card (internal or external). There's no easy way to get that done, seems I have to do some radical change, react to the pressure and put everything on the app-dedicated storage area... I really don't like to because that means all downloaded rd5's are deleted on app de-install...

**Comment by andrixnet** [comment]
Since Android introduced these limitations, many apps had to wrestle with this problem. 
c:geo, osmand, for example, they can use different directories for storage (other then app-dedicated storage area).
- One can customize where osmand downloads and stores it's maps 
(may require user to manually create directories and give app additional permissions)
- one can customize where c:geo exports GPX files
(may require user to manually create directories and give app additional permissions)

Take a look at their code as well.
