### ISSUE TITLE
Add HTTPS support on http://brouter.de

### ISSUE THREAD

**Issue by bagage** [abrensch/brouter#140]
Would it be possible to add HTTPS support on http://brouter.de @abrensch? 

Despite HTTPS pros in general, HTTP is not compatible with brouter-web `show my location` feature.

I can help with [LetsEncrypt](https://letsencrypt.org/) setup if needed.

For reference, I'd initially created an issue on brouter-web bugtracker: https://github.com/nrenner/brouter-web/issues/60

**Comment by abrensch** [comment]
I have some progress on the https option after the switch to an uo-to-date ubuntu 18.04 64 bit linux

-> managed to get a certificate from LetsEncrypt

- managed to write an nginx-config that can do the switch betweenn the static and the dynamic content on the same port, despite of the namespace "near overlap" ( GET /brouter/profiles2 <-> POST /brouter/profile and the like )

Here's a testlink with a modified config.js that derives the backend server adress from it's own origin:

https://brouter.de:4432/brouter-web-ssl-test
http://brouter.de:81/brouter-web-ssl-test

Intention is that this nginx server should replace both the apache (on port 80 ) and the simple proxy on port 443 that's currently forwarding to the backend server.

Still missing is the setup of automatic certificate refresh ( valid only 3 months... )

And I do not yet have a migration strategy for swithing the 443 port from plain HTTP so SSL, because there seems no fast way to fully re-deploy the web-client, so when changing the access the old mechanism will be active for many more hours.

**Comment by abrensch** [comment]
so finally I switched to new new Configuration:

- Port 80 + 443(ssl) via nginx each serving both static and dynamic content
- config.js using it's own origin also for backend server + profile-download url

**Comment by bagage** [comment]
Awesome, thanks @abrensch!
