### ISSUE TITLE
adding Mapillary overlay

### ISSUE THREAD

**Issue by iamnunocaldeira** [abrensch/brouter#143]
great website, use it for setting my routes to uncovered areas on mapillary to improve OSM data. Would it be possible to add the Mapillary layer, so i dont have to add it manually each time?
Mapillary layer:  https://d6a1v2w10ny40.cloudfront.net/v0.1/{z}/{x}/{y}.png
![imagem](https://user-images.githubusercontent.com/15980854/52453657-43636700-2b40-11e9-9e8f-f0b1bfd8df3b.png)

**Comment by Phyks** [comment]
Hi,

This issue is for Brouter-web (the web interface), not Brouter (the routing engine powering it). Brouter-web repo is https://github.com/nrenner/brouter-web

and you can follow https://github.com/nrenner/brouter-web/issues/153 which should cover the same idea :)

**Comment by Phyks** [comment]
@iamnunocaldeira These are raster tiles with location of Mapillary images. Do you know if Mapillary also offers vector tiles or another mean of displaying the images which could also be used to make them clickable and display an embed view of the images?

Thanks,

**Comment by nrenner** [comment]
@Phyks For vector tiles see https://www.mapillary.com/developer/tiles-documentation/, specifically [Image Layer](https://www.mapillary.com/developer/tiles-documentation/#image-layer).

**Comment by nrenner** [comment]
@iamnunocaldeira 
> Would it be possible to add the Mapillary layer, so i dont have to add it manually each time?

A layer added to "Custom layers" should be stored in the Browser and not needed to be re-added. If not, maybe check the privacy settings of your Browser to allow local storage or add http://brouter.de as an exception.

**Comment by Phyks** [comment]
Thanks @nrenner for the link to the Mapillary vector tiles. I had a look and actually the vector tiles are only generated (and available) for zoom 14 :/ They are extrapolated from there in the Mapillary app.

I did not find any way in Leaflet to be able to use them at other zoom levels :/ Do you know about something like this?

Fixing this particular issue is basically just adding the raster tiles to the overlays and is easy to do. Fixing https://github.com/nrenner/brouter-web/issues/153 however, would require being able to display the vector tiles at all zoom levels.

Otherwise, https://github.com/nrenner/brouter-web/issues/153 can still be fixed but requires accessing the Mapillary API to manually create points for images and this is probably a lot of Mapillary-specific code to integrate in brouter-web :/

**Comment by nrenner** [comment]
There is now a "Mapillary Coverage" overlay as optional layer under "More" in brouter-web, so this can be closed.

**Comment by Phyks** [comment]
@iamnunocaldeira Could you close this one please? This should have been fixed in BRouter-web. Thanks!

**Comment by sjakobi** [comment]
@mjaschen Could this overlay be added to bikerouter.de too? It would be really useful for adding missing data to OSM.
