### ISSUE TITLE
Calculate travel speed in profile

### ISSUE THREAD

**Issue by YaroShkvorets** [abrensch/brouter#211]
Right now as far as I understand brouter assumes default moving speed for bikes with some turn/incline compensation.

I think it would make a lot of sense to allow to calculate moving speed in profile. Tags like surface, highway type (steps and sidewalks for example), traffic lights, etc affect speed quite a bit. Also if I'm using Fastbike profile, speed should probably be quite different than Trekking or Safety profile.

Simply introducing `speed` variable (in km/h) and allowing to assign it should do the trick. If it's not assigned in profile - just use existing formula to make it backwards compatible.

Thoughts?

**Comment by Phyks** [comment]
This is already the case, https://github.com/abrensch/brouter/blob/master/misc/profiles2/trekking.brf#L30-L35. Although these params are fixed and not influenced by surface, traffic lights etc.

**Comment by zzptichka** [comment]
I see. As far as I understand since `maxspeed` is declared in global context, so you can't change it based on tags, right?

**Comment by vodie** [comment]
You can use maxspeed in the way context. I use it in the velomobile and recumbent profile to get better travel time estimations by restricting the speed to the allowed maxspeed.

**Comment by zzptichka** [comment]
If I add `assign maxSpeed = 15` to way context I get some wrong Travel time numbers: "596523:14 h"

**Comment by vodie** [comment]
I think you messed up the other travel time estimation parameters as this parameter is just the maximum speed. The speed can be lower if there is steep enough uphill, to little power, to high air or rolling resistance. With high costfactor walking speed is taken and the maxspeed in the global context is taken if it is lower than that in the way context.

**Comment by pipo65rp** [comment]
Hello Guyz
Sorry I reactivate this topic related to time/speed travel.
If I understand well, the main (but not the only) parameter to calculate the time of a route is the "bikerPower".

Can I suggest to give users the possibility to enter average speed (km/h) instead of biker power?
I do a lot of bike travel and honnestly I don't know my bike power...but over the years I know much better the average speed I can manage on bike depending on the distance / elevation I want to do.

By the way thanks a lot for all the work you have done with this website....this is amazing !!

Many thanks

Philippe

**Comment by poutnikl** [comment]
@pipo65rp The point is, the bike power is direct input of the bike kinematic model the author has implemented to BRouter internal.  From it is calculated immediate speed, considering part of the power is spent on rolling (surface and tyre dependent), part of wind drag and part on the slope climbing. Using Average speed is a parameter hard to work with, considering different surfaces and altitude profiles

Working with the bike power is easy. You need not to know you bike power. In fact, you accomodate the profile to the bike power value that produces ETA close to real ETA for the route you know or recently passed, considering bike load and physical effort. 
You can have 2 otherwise identical profiles, one "light mode" with no load, short and sporty ride, one "heavy mode", the bike loaded for long and slow travelling.

E.g. I use in my [beta version of profile template](https://raw.githubusercontent.com/poutnikl/Trekking-Poutnik/develop/Trekking-Poutnik.brf) for "expedition mode travelling"  the bike load ( me+bike+luggage) 120 kg and bike power 85 W, what effectively gives me realistic ETA with implicitly included  physiological, relaxation, refrshment or sightseeing stops.

**Comment by poutnikl** [comment]
@pipo65rp  Average speed could be trivial to implement, but it is a "one size fits all". It would fit an average route, but would give optimistic ETA estimations for difficult routes and pesimistic for easy ones.

The bike power is effectively an adaptive parameter of the average effort, giving longer ETA for more difficult routes and short for easy ones. 

It is direct input of the bike kinematic model the author has implemented to BRouter internals to provide ETA for bike routes. From this power is calculated immediate speed, considering part of the power is spent on rolling (surface and tyre dependent), part of wind drag and part on the slope climbing. 

Working with the bike power is easy. **You need not to know you bike power.** In practical usage, you accomodate the bike power value for your personal conditions to produce ETA close to real ETA for the route you know or recently passed, considering total bike mass and physical effort.  
 
- Take the known ETA, the profile you have used for it, (or would use). 
- Set an initial power, e.g. 100W. 
- Calculate ETA (Easy e.g. in the LocusMap route planner)
- If it is longer than the known ETA, increase the power  ( or vice versa) 
- Repeat the last previous steps until theknown and calculated ETA approximately match.

E.g. I use in my [beta version of profile template](https://raw.githubusercontent.com/poutnikl/Trekking-Poutnik/develop/Trekking-Poutnik.brf) for "expedition mode travelling"  the bike load ( me+bike+luggage) and bike power 85 W, what effectively gives me realistic ETA with implicitly included short stops for whatever usual reasons.

**Comment by quaelnix** [comment]
> With high costfactor walking speed is taken and the maxspeed in the global context is taken if it is lower than that in the way context.

@vodie, this is no longer the case, see: https://github.com/abrensch/brouter/pull/495

> Simply introducing speed variable (in km/h) and allowing to assign it should do the trick.

> Can I suggest to give users the possibility to enter average speed (km/h) instead of biker power?

@YaroShkvorets, @pipo65rp, simply set the `bikerPower` to `2000` (or any other high number) and then set `maxSpeed` to your desired average travel speed ... done!
