### ISSUE TITLE
No penalty for highway=footway in the trekking profile

### ISSUE THREAD

**Issue by polyscias** [abrensch/brouter#225]
I was debugging some issues related to routing and in the end the problem seems to be that there is no penalty for highway=footway, at least in the default trekking profile.

http://brouter.de/brouter-web/#map=19/51.91651/4.48112/standard&lonlats=4.479926,51.916305;4.481065,51.91639;4.482151,51.916304

Here the bicycle route is "forced" over highway=footway but $/km is still "default":

![Trekking_profile_footway png](https://user-images.githubusercontent.com/6134878/74085161-12c54e80-4a6e-11ea-88ce-d9114521c790.png)

If you remove the blue marker the total cost goes down from 545 to 317 so normally you will not be routed over the footway but this is just an example to make things clear.

As the route is more than half over highway=footway I expect the cost to be at least 3 times higher than the normal route as you should not cycle but walk.

Isn't the trekking profile missing something like:

```
diff --git a/misc/profiles2/trekking.brf b/misc/profiles2/trekking.brf
index df4b06a..25d274d 100644
--- a/misc/profiles2/trekking.brf
+++ b/misc/profiles2/trekking.brf
@@ -216,6 +216,7 @@ assign costfactor
   # some other highway types
   #
   if      ( highway=pedestrian                ) then 3
+  else if ( highway=footway                   ) then 4
   else if ( highway=bridleway                 ) then 5
   else if ( highway=cycleway                  ) then 1
   else if ( isresidentialorliving             ) then ( if isunpaved then 1.5 else 1.1 )

```

**Comment by abrensch** [comment]
Thanx.

The effect is special to footways with no access-tagging but a surface tag.

I changed it (in GitHub, will be deployed on the server later) - had to change it in the access logic, but then extend the "probalbyGood" term to avoid double-counting.

In your example it' correct now in the sense that the costfactor is 5 (=pushing speed), but it doesn't change the routing result, because the reverse oneway still has a higher cost.

regards, Arndt
