### ISSUE TITLE
Error "null description for: n_..._..."

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#254]
`curl -v "http://localhost:17777/brouter?lonlats=9.401579,47.806022|9.401146,47.805785&profile=trekking&alternativeidx=0&format=geojson"`

returns this error:

```
null description for: n_8570957_50000629
```

The coordinates are exact positions of two subsequent nodes. I encountered this while testing the new [load track as route (#312)](https://github.com/nrenner/brouter-web/pull/312) feature, loading an exported track and tuning fuzziness to minimum, so that it uses every node as route waypoint (probably a bit too much). Only some segments cause errors.

BRouter-Web URL with two other cases nearby:
http://localhost:8080/index.html#map=17/47.80515/9.40472/osm-mapnik-german_style&lonlats=9.405888,47.806629;9.401579,47.806022;9.401146,47.805785;9.400571,47.805284;9.400452,47.805073;9.400356,47.804424;9.399382,47.803467

**Comment by abrensch** [comment]
actual problem seems to be that the routing does not find a result and runs forever

The "null description for" I guess is just an assertion that fails because you are using "mixed" data (rd5-files of different age) as you can see from the coordinate of the error node ( n_8570957_50000629 means at latitude = 50 degree ), and because the routing would run forever it hits the tile boundary.

I was wondering in the past if I should remove that assertion, but anyhow, it does it's job, as using mixed data is not supported.

The actual problem is a "fuzziness" in handling "same-segment-searches". In edge cases it happens that this logic does not consider any of the 2 start-paths to be "direct" (pointing from start to destination).

I added an additional detection logic for directness, and already deployed that patch on the server instance.

Biut still not okay. These searches now return "single-node" results. Seems I need another patch for that, will come back on that issue

**Comment by abrensch** [comment]
did a major rework of the "same segment search" logic now.

so should be o.k. now

even some other edge-cases, like routing against a oneway or over a nogo with start- and endpoint on the same way section.

**Comment by nrenner** [comment]
Thanks for the quick fix!

Can confirm that other cases are also running fine now.
