### ISSUE TITLE
brouter routes over closed (access=no) bridge (trekking profile)

### ISSUE THREAD

**Issue by momu** [abrensch/brouter#256]
Considering [this route][1] `brouter` (`BRouter-Web 0.12.0`) routes over [this bridge][0] which is tagged like this when using the `Trekking bike` profile:

```
access=no
bridge=yes
highway=track
layer=1
tracktype=grade2
```
The bridge is where the white dot is:

![image](https://user-images.githubusercontent.com/1451642/86032476-b7552680-ba37-11ea-9826-2a38ffd8b746.png)

I think this is wrong and `access=no` should be avoided when routing by bike. 

[0]: https://www.openstreetmap.org/way/93541569

[1]: http://brouter.de/brouter-web/#map=15/53.8324/12.0139/standard,Waymarked_Trails-Cycling&lonlats=12.013282,53.825381;12.007705,53.839868

**Comment by abrensch** [comment]
we had this discussion before.

Your observation is true for th trekking profile, where the existance of a bike route relation overwrites the access tag.

The fastbike profile for example does not do that.

It's not easy to change because that would probably break many many bike route relations where access tagging is just wrong or sloppy.

But of course you can use a modified profile if you don't want that

**Comment by nrenner** [comment]
@abrensch 
I already wanted to start a FAQ and did so now:
https://github.com/nrenner/brouter-web/wiki/FAQ

Would probably make sense to move that question to this repo (GitHub Wiki is editable for anyone by default, so I could do that). What do you think?
