### ISSUE TITLE
Voice hint for route point on junction node

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#282]
Reported by @EssBee59 in [brouter-web#356 "voice hint generation" after "Load Track as Route"](https://github.com/nrenner/brouter-web/issues/356).

In this simplified example with a left turn, a wrong "turn right" hint is generated (e.g. with turnInstructionMode=3 osmand-style):
http://brouter.de/brouter-web/#map=17/50.03360/8.73385/standard&lonlats=8.732253,50.033975;8.733453,50.032993;8.735944,50.03403

The via point is exactly at the position of the junction [node 269491681](https://www.openstreetmap.org/node/269491681) (rounded to 6 digits). As each route segment is calculated separately, I would have expected that no voice hint can be given. 

Therefore I guess we need to move the via points a bit when converting a track to a route in the client anyway, as the Douglas-Peucker simplification probably tends to leave junction nodes at turns.

This minimal example without turn, only two route points and the destination on the junction node also generates the voice hint:
http://brouter.de/brouter-web/#map=17/50.03359/8.73189/standard&lonlats=8.732253,50.033975;8.733453,50.032993

**Comment by EssBee59** [comment]
Hello,

In #356 I explained a workarround to this problem:
As sugested by Norbert, after the conversion of the track to a route, the idea is to change the created route-points in order to avoid setting them exactly to junctions.
A  "new" route-point is now calculated in my version as the middle of the "raw" route-point and his previous trkpt in the original track.
The change can be tested on this instance:
http://brouter.de/essbee/#map=11/49.9576/8.5752/standard

I hope the change (or a similar or a better one) will be accepted as standard and deployed in the Brouter-web.
Regards

**Comment by 0709wiwiwi** [comment]
@EssBee59 
Nice that you are investigating this. But it remains a difficult task anyway.

I have tested next import file  on the mentioned web router.
[TET_trk_download.gpx.txt](https://github.com/abrensch/brouter/files/8796110/TET_trk_download.gpx.txt)
At import I kept the default 'fuziness' setting. Routing Profile: (Fastbike-very low traffic).

Detection of possible trackglitches.
Too time-consuming detection U-turn alerts. On a quick check I notice 2 trackglitches. 
So in those places expect confusing turn instructions.

Since mistakes are so hard to avoid, show_trace the suspected locations and correct manually to the best of your ability and insight.

Regards, Willy.

**Comment by EssBee59** [comment]
Hello,
I started the test described above an generated "Osmand" turn instructions:
For me, the generated TU are perfect!
I agree, at 3 places, it could be confusing, but the track at these places is very special...

![image](https://user-images.githubusercontent.com/50321352/171045478-12db3ead-ad4b-4f7e-a1b3-dfb8d13c89ec.png)
![image](https://user-images.githubusercontent.com/50321352/171045591-9523d417-258d-4f16-9499-307f4092352d.png)
![image](https://user-images.githubusercontent.com/50321352/171045657-cacefe20-80be-4aac-a588-db0e4c396a26.png)

In such "special" (crazy) cases I do not expect a perfect result

**Comment by EssBee59** [comment]
Hello 0709wiwiwi,

I agree, in 3 locations "confusing turn instructions" are generated!
I think, the quality of the original track is responsible for this:
Some poinst are very strange (outside the route), in other places, due to a long distance between 2 points, the track line is also many meters outside the route.

![image](https://user-images.githubusercontent.com/50321352/171104556-b3787661-07d6-49a7-aff7-160006b2755d.png)

![image](https://user-images.githubusercontent.com/50321352/171104614-5c8b2aca-3b79-4335-9662-6a651f83272e.png)

![image](https://user-images.githubusercontent.com/50321352/171104640-53ac4e3c-673e-4377-b589-7429caad17cf.png)

**Comment by 0709wiwiwi** [comment]
Sure, If you convert the track for Locus as described (with attachment of turn instructions by BRouter web), it is with errors.

Usually I, **a gps user**, limit myself to the Locus results with the plug and play ready attached instructions by BRouter web.
Due to the A11 problems the Locus gps development paused for a while, so I made a very instructive trip to the Kurviger app. 

Crazy track(s). 
Unfortunately, there is a lot of imperfect track material available for download on the internet.That's just a fact.
No matter how hard designers (thank you, thank you) try to improve results, there are no miracle solutions.

I already carried out dozens of similar tests, by now I so simply accept such unavoidable imperfections.
Should not be a real operational problem when a tool is available to detect an show the trouble spots.
What interests me, **a gps user**, is a quick tool that shows me where exactly there may be errors.

The tested Kurviger app with its U-turns in the turn list is in my experience been the most helpful tool. 
That is why I plead for the Brouter to generate the very functional (180°) U-turns just like the GH engine.
The tool is so useful both for a completely manual new design and for an automatic track conversion. 

In Kurviger, you detect the U-turns in the turnlist and deal with the corresponding triggering planner point.
What is not yet been implemented in the app is a fast nice on map indication of the problematic locations.

**Comment by EssBee59** [comment]
Hello brouter experts,

I spend last year a lot of time to search the cause of the original problem (voicehint generation when a route point has exact the same position as a junction node)

Now I had a look at the code and I suspect the following behaviour to be the cause of the problem:
- The "RoutingEngine" calculates the track for each part of the route (from a route-point to the next)
- If several route-points are entered, the tracks are added together: This is OK!
- But the RoutingEngine calls in the same way the "ProcessVoiceHints" for each part of the route....
and I think this leads to the problem of this issue!!!
(without knowledge of the previous track-point, the angle at the junction / start point can not be calculated)
A redesign should be done to call "ProcessVoiceHints" for the total route at once!

**Comment by poutnikl** [comment]
If BRouter knows, what the total route is.....

**Comment by 0709wiwiwi** [comment]
Hello EssBee59.

First example. The false turninstructon.
The exported gpx locations are rounded to 6 digits.
The via point you import is rounded to 6 digits.

"The via point is exactly at the position of the junction node 269491681. 
Is it ? 
The Via Point that you import is 50.032993, 8.733453 (6 digits)
The junction node location is: 50.0329928, 8.7334534 (7 digits)
The route point location is different from the junction node position. 

Q: What (digits) are used internally in the BRouter ?
By that generates the false turninstruction ? (rtept is more West)

**Comment by polyscias** [comment]
>  * The "RoutingEngine" calculates the track for each part of the route (from a route-point to the next)
>  * But the RoutingEngine calls in the same way the "ProcessVoiceHints" for each part of the route.... 
>     and I think this leads to the problem of this issue!!!

100% agreed, that is what I already wrote in https://github.com/abrensch/brouter/issues/436#issuecomment-1136364940

I also still think we need to have functionality to snap via points to the way network, especially if the via point are close to crossing.

**Comment by polyscias** [comment]
Yes and no, trackpoints are not snapped to the way network in the sense that the track contains a line from the actual trackpoint to the point on the closest way of the way network. That is typically no problem for via points as long as they are not close to a crossing.

I think that in almost all cases the user will be happy if the waypoint is moved to be on the way-network; I am eager to hear reasons for not doing so.

**Comment by 0709wiwiwi** [comment]
You can even see in the actual BRouter where the Via Point has his corresponding trackpoint located. 
Near the planner point Via or Shaping you do noticea fine little small line over the visual track. No ?

**Comment by EssBee59** [comment]
> If BRouter knows, what the total route is.....

Hi Polischias,
In the requests to Brouter (from brouter-web or Navi-apps) many route-points can be specified.
In the example of this issue with brouter-web, a track was previously loaded as route...
(assuming 50 route-points were generated and coded in the URL of brouter-web)

As result, brouter-web send a similar rquests to brouter with 50 route-points...
The problem I see, currently the brouter  calculates the 49 tracks between this points separatly and concatenates these 49 tracks to get the total track...
But it do the same for the voicehints!

The problem is, when as example the point between track 1 and track 2 needs a voice hint (as it is a node), who is responsible for that / who can produce the voicehint?
To produce the right voicehints, track1 and track2 must be processed in the same run / together!

**Comment by polyscias** [comment]
> To produce the right voicehints, track1 and track2 must be processed in the same run / together!

Yes, like I wrote above, I already did 100% agree on that ;-)

@0709wiwiwi : Yes, correct, I was wrong, no line from the waypoint to the neatest way is drawn. 

Still I think that if there is a crossing nearby, the waypoint is better snapped to that crossing.

My proposal would be: Take the distance to the nearest way using the method that is currently used, let call that Lw. Now check if there is a crossing within 1.5*Lw distance of the waypoint and if so, take that crossing.

**Comment by 0709wiwiwi** [comment]
**Automatically convert a track into a track with navigation instructions.**
(I avoid the expression convert to route because that is it not either)

@EssBee59

The example with what the "user" experiences as being a wrong turn instruction Right.

Which voicehints do you expect at the 'snapped' planner point positons ?
There are two instructions which belong exactly to the planner point position.

1. A continuous or straight. 
As I am already riding forward, this straight is not necessary and even undesirable.
At shaping points I do not want any announcement, no sound, no symbol, no auto display on.

2. A U-turn. 
A U-turn command (usually unwanted) is what I want for sure. Serves as alarm sign !
BRouter does not generate U-turns. A possible nice alarm sign but the light is missing. 
The U-turn would otherwise tell you that your planning point is not well positioned.

In the example, the turn instructions (near the snapped planner point position) are technically correct.
However, the planner point is at the wrong position. So triggers a Right but the next U-turn is missing. 
In order for this to be considered correct, the planner point should so be snapped onto the further track to be followed.

So, automatic planner point position corrections, but how?  
Moving the planner point position ? In which direction? How far? 
The planner point position is wrong and fiddling will not get it right.

Does the planner point trigger an unwanted U-turn? 
Then be bold and remove the planner point.
Do as a good surgeon does, don't hesitate, cut. 
Even then, there are enough planner points left to calculate.
A human operator final "follow-up check" is still always needed.

=========

Another convert example video by using the Cruiser_Brouter app. 
https://youtu.be/MmedcoEtupo
Calculation (fast) using distance tickmarks from the import track.
Without U-turn, the single wrong planner position is quite difficult to find. 
Using tickmarks there are less critical planner points near junctions.

**Comment by afischerdev** [comment]
@EssBee59 

>     * But the RoutingEngine calls in the same way the "ProcessVoiceHints" for each part of the route....
>       and I think this leads to the problem of this issue!!!
>       (without knowledge of the previous track-point, the angle at the junction / start point can not be calculated)
>       A redesign should be done to call "ProcessVoiceHints" for the total route at once!

Thats what I try with the  #441. The point to point tracks are collected as well as the detours. And at the end the voice hint process is called. 

Your very first sample in this thread comes now like this:

[testtrack0.same_pts.gpx.txt](https://github.com/abrensch/brouter/files/9009278/testtrack0.same_pts.gpx.txt)

**Comment by EssBee59** [comment]
> Thats what I try with the #441. The point to point tracks are collected as well as the detours. And at the end the voice hint process is called.

Hello,
I restarted a first test using version 1.6.4 and found no voicehint-errors !
Gratulations to the change!


I will try to start further tests in the next days...and will report in #441 (about problems not concerning voice-hints)

**Comment by nrenner** [comment]
This issue only came up because the "load as route" feature in the client, that programmatically generates via points at node positions with a bias for junctions ([brouter-web#356](https://github.com/nrenner/brouter-web/issues/356)), so I suppose it's a rare edge case otherwise that might not need fixing.

There is a proposed workaround for that, it just needs some more work before merging: [brouter-web#369 ](https://github.com/nrenner/brouter-web/pull/369).

The wierd thing is just that it always generates a right turn instead of just none or maybe some kind of "heads up" warning (maybe "[Off route](https://github.com/abrensch/brouter/blob/9d37e2c6485f43f0c08e7aa89fe4c813d1cd2d66/brouter-core/src/main/java/btools/router/VoiceHint.java#L25)").

**Comment by EssBee59** [comment]
> The weird thing is just that it always generates a right turn instead of just none or maybe some kind of "heads up" warning

Hello Norbert,
I did not know about that...
For me the workarround I suggested (not using the junction point, but the middle of junction point and last track-point) is running, could you give some details?
The bad thing: by testing #441 I discovered further problems:
Not only "voiceHints" are in error:
some times, the generated track is in error after a load "track as route"

http://brouter.de/brouter-web/#map=16/50.0078/8.8099/osm-mapnik-german_style&lonlats=8.799857,50.004894;8.808872,50.007659;8.80993,50.007943;8.810851,50.006446;8.81355,50.003108;8.814458,50.002141;8.815893,50.000959&profile=fastbike

![testcase_2_TrackError](https://user-images.githubusercontent.com/50321352/176949937-e12bceaf-13fe-40e5-b988-625c37570bc3.jpg)

**Comment by nrenner** [comment]
>> The weird thing is just that it always generates a right turn instead of just none or maybe some kind of "heads up" warning
> For me the workarround I suggested (not using the junction point, but the middle of junction point and last track-point) is running, could you give some details?

I don't mean your solution, I'm just referring to this issue, see issue description in first comment.

**Comment by afischerdev** [comment]
The library is generated by git [actions](https://github.com/abrensch/brouter/actions/runs/2616963303). The ZIP below on side contains new jar file.

**Comment by EssBee59** [comment]
Hello,

My retest was not successfull:

Firtst, I liked to describe my 2 use cases:
A- My bike-club organizes every year bike tours (so called RTF in germany), 4 different routes are defined.
But the routes have to be changed a bit every year ....(this year we had to build 3 changes each after one)

B- Most of the time the GPX I receive have only a track, and I enrich the GPX with voiceHints to get the best guiding
 
For that, I am using the feature "load track as route" in brouter-web, I modify the route by need, select the right turnInstructionMode and export the new track (kinf of reexport)

And exact in this situation (in the origin track, points are = node/junction)  as reported in this issue "voiceHint" issues occur, worst, some times Routing issues occur too.

No idea how many users are using Brouter in this way. 

I attach a new example:
1- the origin track 
2- the reexported gpx using brouter.164 (track and route with voicehints for Osmand)
3- the reexported gpx using brouter.163 and brouter-web 0.16.0 + my own workarround in "load track as route"

"gpx 2" contains many issues ( voiceHints and routing) 
[47km_original.gpx.txt](https://github.com/abrensch/brouter/files/9053310/47km_original.gpx.txt)

[47km_Brouter164_New.gpx.txt](https://github.com/abrensch/brouter/files/9053314/47km_Brouter164_New.gpx.txt)

 
[47km_essbee.gpx.txt](https://github.com/abrensch/brouter/files/9053317/47km_essbee.gpx.txt)

**Comment by afischerdev** [comment]
@EssBee59 
Great sample. So I found my fail. But I have one more unexpected direction before I will have a view on voicehints.

**Comment by EssBee59** [comment]
> This tool places almost no routepoints on road intersections.
> How the designer Jaco manages to do this I do not know.
> But no routepoints at road junctions is the key to success.

Hello,
I agree, I am using a similar workarround since 2 years.

Sorry, I do not understand what your test do exactly (possible translation issue?):
- The generated route is not optimal: as example the U-turn in Eppertshausen (catering place for the bikers!)  do not appear.

- "merge the original track in the GPX" ...is not what I want: my goal is to apply a minor change to the route and "re"-export the new track

**Comment by poutnikl** [comment]
> Profile fastbike with add assign avoidPeaks = 0

Is avoidPeaks a variable of customized/not yet published fastbike profile, or recently implemented system variable?

**Comment by EssBee59** [comment]
> Great sample. So I found my fail. But I have one more unexpected direction before I will have a view on voicehints.

Again, thank for working on that!
As my workarround is quite running, feal free to decide how much time you can invest in these special problems.

But I try to help and created a detailled documentation of the new detected "routing issue" (not voiceHint)
regards
[routing_nok.pdf](https://github.com/abrensch/brouter/files/9062679/routing_nok.pdf)

**Comment by EssBee59** [comment]
Hello,

Brouter-web is using the "turf.simplify" utility (https://www.npmjs.com/package/@turf/simplify)
The trkpt´s are given as input (+ a tolerance prameter that impact on the number of route points that will be created), a list of route points is returned (= reduced point list)
I attach the java-scrit module that also contains my workarround 
regards

[RouteLoaderConverter.js.txt](https://github.com/abrensch/brouter/files/9063964/RouteLoaderConverter.js.txt)

**Comment by 0709wiwiwi** [comment]
@EssBee59 

Do you know the Cruiser app?
The original included track is only imported as a passive template to visually check if the new recalculation result matches.
And I have now added you the used import test file. Currently nothing automated, manual preparations are required. 

Converting tracks to add turn instructions automatically is quite useless up till now.
The necessary checking of the result is more time-consuming than manual retracing.
**You absolutely must catch wrong instructions already in the design and not during cycling.**
So a U-turn alerter is already a first aid tool that can point out the turn errors more quickly.

I am not going to solve this difficult task here either, but simply share how I tested so far.

What is the intention? Avoiding routepoints onto road junctions as much as possible. 
What if there remains unexpected U-turns either ? Eliminate U-turns by deleting the corresponding routepoint. 
There are enough routepoints still left to reproduce the original trackpath.  
Is the new calculated track result different?  Adjust by the visual  import track template.

So please find a second test file by another method intended for Cruiser_Brouter import.
[Ready for Cruiser NI_trk_47km_rte_0.5km_tickmarks.gpx.txt](https://github.com/abrensch/brouter/files/9065284/Ready.for.Cruiser.NI_trk_47km_rte_0.5km_tickmarks.gpx.txt)

Here by using fixed track 0.5km distance tickmark routepoints. (Max 200).
Video: https://youtu.be/FPqvpPrt7h8
The new calculated track will be more faithful, but the chance of U-turns increases.
Find unexpected harmfull U-turns in the turn list and eliminate the corresponding routepoint.

THE QUESTION. 
Even if completely automated, does it save you time compared to manual retracing? Y or N ?
Because a final check on the track fidelity and U-turns remains necessary.

@poutnikl 
This was needed for a non preliminary BRouter test apk.

**Comment by 0709wiwiwi** [comment]
@EssBee59 
No no,  it's definitely about Brouter and BRouter web promotion. 
But with the current BRouter web I can't show what is now possible with an app, me whatever app. 
The app you don't like, allows me to show the import track on top of the recalculated track and is therefore a best demo to compare.  Continue in text attachment.
[Save design time and get a quality result or not.txt](https://github.com/abrensch/brouter/files/9069130/Save.design.time.and.get.a.quality.result.or.not.txt)

**Comment by poutnikl** [comment]
Improving on-topic apps sometimes takes off-topic ones.

**Comment by afischerdev** [comment]
Repair of waypoint matcher is out. You find it in git [actions](https://github.com/abrensch/brouter/actions/runs/2635129684) in the ZIP file.

Next part I like to have a view on the voicehints. Based on the route points in EssBee59 [Neu-Isenburg_47km_rte_trk.gpx.txt](https://github.com/abrensch/brouter/files/9060898/Neu-Isenburg_47km_rte_trk.gpx.txt) file.

**Comment by EssBee59** [comment]
My retests:

Brouter version 1.6.4 of this morning and brouter-web 0.18.1:

Test data: 10 tracks (generated with brouter), summary 1.000 km

test scenario: "load track as route" and reexport

results: 0 "routing" error detected!

Very good job!

I will try to execute further tests next week and report by need

regards

**Comment by EssBee59** [comment]
further tests: calculate 3 new routes (70 km, from A to B) and compare the results of 1.6.3 and 1.6.4:

No problem found!

**Comment by 0709wiwiwi** [comment]
Concerning the BRouter turn instructions and the Voice hint generation.

A cycle route that largely follows an old railway line seems to be quite a challenge for the Brouter. 
Brouter definitely sees more turning in it than the locomotive drivers ever did in the past.
Attached the gpx file export in the Locus (7) compatible navigation track format from the RouteYou web planner. 

[routeyou-zelzate-eeeklo-i55-oude-spoorweg-route-locusmap.htm.txt](https://github.com/abrensch/brouter/files/9239529/routeyou-zelzate-eeeklo-i55-oude-spoorweg-route-locusmap.htm.txt)
[routeyou-zelzate-eeeklo-i55-oude-spoorweg-route-locusmap.gpx.txt](https://github.com/abrensch/brouter/files/9239530/routeyou-zelzate-eeeklo-i55-oude-spoorweg-route-locusmap.gpx.txt)

**Comment by afischerdev** [comment]
@0709wiwiwi 
I'm not sure if I understand you right. From my point of view everything looks well. Old spooway is not defined all over the way. 
Could you tell us please what points you see faulty.

**Comment by 0709wiwiwi** [comment]
I retested by by Bikerouter.de and that result is indeed fine.  

https://bikerouter.de/#map=17/51.19887/3.62578/standard&lonlats=3.79456,51.208156;3.704341,51.247367;3.637936,51.223555;3.589921,51.17769;3.574242,51.181758

(Except for some unexpected slight instruction it is sure ok to use)

Find the Bikerouter result also in the htm.
[Zelzate -_ Eeklo (22.5km)_Locus(2) by BRouter web.htm.txt](https://github.com/abrensch/brouter/files/9242300/Zelzate.-_.Eeklo.22.5km._Locus.2.by.BRouter.web.htm.txt)

I so tested again by the current Cruiser_Brouter app combination. 
(BRouterApp.1.6.4g-release.apk)
And I copied and so used that same trekking.brf file as was used by Bikerouter.de

result has false instructions and surprisingly routes even direct over that motorway.
As Cruiser does not export a plug and play ready to go gpx navigation track  :-(( 
So I can't easily share you that results inclusive the turn instructions.
(But Locus map by the same Brouter apk and profile is also not ok and does also not match the Bikerouter.de result)
Any idea ?

The imported file with the reference  wpt's to be used for the routing in the Cruiser_Brouter app combination.
[Zelzate -_ Eeklo (22.5km)_None (0_wpt).gpx.txt](https://github.com/abrensch/brouter/files/9242363/Zelzate.-_.Eeklo.22.5km._None.0_wpt.gpx.txt)

**Comment by afischerdev** [comment]
@0709wiwiwi 
The way points gpx was very helpful.  It shows where the route is about.
But I got a different result to your first and second sample.
1. routeyou sample doesn't use the tunnel under the road A11
2. bikerouter sample has same problem but other result and it doesn't use the spoorway around Assenede.

For this gpx I used lib 1.6.4, trekking and Locus output.
[testtrack0_spoorway.gpx.txt](https://github.com/abrensch/brouter/files/9243891/testtrack0_spoorway.gpx.txt)

It is hard to compare when apps don't use the sample profile. I know Locus uses its own profile and send it to BRouter. But I can't say what Cruiser is doing.

**Comment by 0709wiwiwi** [comment]
There is no tunnel under the road A11. 
You have to pass by the traffic lights.  (Dangerous crossing anyway !!)
Locus uses the same Brouter app by the same identical trekking profile as Cruiser does.

Result Locus app is: 
[Zelzate-Eeklo_Locus_app_trekking_ap0_navwpt.gpx.txt](https://github.com/abrensch/brouter/files/9243943/Zelzate-Eeklo_Locus_app_trekking_ap0_navwpt.gpx.txt)
attached.

**Comment by devemux86** [comment]
> But I can't say what Cruiser is doing.

Cruiser uses what is described in [IBRouterService](https://github.com/abrensch/brouter/blob/master/brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl):
- BRouter app: "v" --> [motorcar|bicycle|foot]
- Brouter website: "profile" = profile file name without .brf
[car-fast|fastbike|trekking]

It does map custom profiles, this is left for the user (as described [here](https://forum.kurviger.de/t/app-offline-routing-brouter/649/19)).

**Comment by afischerdev** [comment]
@0709wiwiwi 
> There is no tunnel under the road A11.

I can see one in OSM. And the Locus routing also use this tunnel.
Defined: highway=no railway=abandoned tunnel=yes and a biker route 'F423 Fietssnelweg Kaprijke'

@devemux86 
Thanks for the clearing.

**Comment by 0709wiwiwi** [comment]
I can have a look later at that osm edit there, altough I only do correct the local mistakes usually.  
But for 100% sure there is no tunnel there. (Probably someone did add that old railway ?) A steammachine lover ? 
Open street map anyway is very vulnerable for such mistakes.  And I know that osm is not a very reliable (but free) data source
A few years ago in my own region I so noticed a railway, but is was one that already was out of service and disappeared completely since +/- 60 years ago).

The bikerouter.de result by using the standard trekking profile is so correct. 
Changed was the turninstructionCatchingRange = 4.

This also demonstrates the multiple problems, you as a gps user, usually than get when sharing and using (rte) routes. 
Calculation by reference wpt's or by rtept's, you frequently do get a different result with the original planned design. :-((
The slightest difference in router engine or profile or routing data are causing than unexpected changes and results.
By sharing  a plug and play, ready to go, gpx navigation track inclusive integrated instructions in trkpt such trouble does not occur. Always transfer 100% faithfull designs, this on the condition of course that no recalculation nor (auto)rerouting is allowed after import in the navigation app.

**Comment by carg0cult** [comment]
This bug is still present on brouter.de/brouter-web. Many turn instructions are generated in the wrong direction. I tested an example on brouter.de/essbee and it was correct. Could you please apply the fix to brouter.de/brouter-web or what needs to be done? Maybe I can help.

**Comment by 0709wiwiwi** [comment]
1. If route(way)points are correctly placed (manually or automatically) then Brouter does NOT generate unexpected (very) short track tails NOR generates any "false" turn instruction.

2. The already tested **Cruiser**_BRouter Beta app by "afischerdev" recognises suspected misplaced route(way) points and prevents damage by correcting their location.

3. The **Cruiser**_Brouter Beta app is flexible and thus still allows producing a well-planned track tail including the very useful U-turn instruction at the 180° track turnpoint. 

The necessary official app update that addresses such unplanned and unexpected "false" turn instructions has still not been published.

Why the updating process is that slow is not known to me.

Translated with www.DeepL.com/Translator (free version)
