### ISSUE TITLE
Running brouter in debug mode

### ISSUE THREAD

**Issue by joshuapassos** [abrensch/brouter#287]
Its possible to run the http server in debug mode? 
If yes, how i do it?

**Comment by nrenner** [comment]
I debug in the IDE, haven't tried otherwise. There is a run/debug configuration [RouteServer.xml](https://github.com/abrensch/brouter/blob/master/.idea/runConfigurations/RouteServer.xml) for [IntelliJ IDEA](https://www.jetbrains.com/idea/), which could also serve as an example for other IDEs.

The main class for running/debugging is [btools.server.RouteServer](https://github.com/abrensch/brouter/blob/372a04a6cf4608cf14bc7045aed9499012a23f52/brouter-server/src/main/java/btools/server/RouteServer.java#L286) in the [brouter-server](https://github.com/abrensch/brouter/tree/master/brouter-server) module, example program parameters are: `misc/segments4 misc/profiles2 ../customprofiles 17777 1 localhost`, see also [server.sh](https://github.com/abrensch/brouter/blob/master/misc/scripts/standalone/server.sh).

**Comment by joshuapassos** [comment]
It's works! thank you
