### ISSUE TITLE
Possible off by one when rounding negative numbers

### ISSUE THREAD

**Issue by phdoerfler** [abrensch/brouter#304]
I wanted to see if there was any [`java.math.RoundingMode`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/RoundingMode.html) that corresponded to the way `ilon` and `ilan` are typically calculated in the [source](https://github.com/abrensch/brouter/blob/master/brouter-server/src/main/java/btools/server/request/ServerHandler.java#L229-L230) but there isn't. Adding .5 and then truncating to Int does have a bias towards positive infinity, does it not? Is this intentional? This is the first time I ever dabbled with OSM so maybe that's how it's done, but it seems very odd to me.
For positive values it behaves exactly as [`HALF_UP`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/RoundingMode.html#HALF_UP), which described as being "the rounding mode commonly taught at school":

```
*<tr><th scope="row">5.5</th>  <td>6</td>
*<tr><th scope="row">2.5</th>  <td>3</td>
*<tr><th scope="row">1.6</th>  <td>2</td>
*<tr><th scope="row">1.1</th>  <td>1</td>
*<tr><th scope="row">1.0</th>  <td>1</td>
```

However, for negative values it behaves like `HALF_UP` **+1**.
While `HALF_UP` does the following for negative numbers…

```
 *<tr><th scope="row">-1.0</th> <td>-1</td>
 *<tr><th scope="row">-1.1</th> <td>-1</td>
 *<tr><th scope="row">-1.6</th> <td>-2</td>
 *<tr><th scope="row">-2.5</th> <td>-3</td>
 *<tr><th scope="row">-5.5</th> <td>-6</td>
```

…this custom rounding scheme does the following…

```scala
Seq(-1.0, -1.1, -1.6, -2.5, -5.5).map(d => (d + 0.5).toInt)
// val res8: Seq[Int] = List(0, 0, -1, -2, -5)
```

…which is exactly what `HALF_UP` does, offset by one towards positive infinity.

**Comment by abrensch** [comment]
It does not make sense to talk about a bias for the lon -> ilon transformation, because that's just "per definition".

And, btw, the idea of transforming into an all-positive integer space is a clever one, because it does not only save trouble in rounding issues, but also in the divide/modulo logik when calculating micro-tile indices and offsets.

When talking about a bias you should look at the digitization error of the full  lon -> ilon -> lon transformation chain.

And this is 0 on average and +-5e-7 maximum only if I apply the "+0.5" int the lon -> ilon transformation.
