### ISSUE TITLE
Changes with 1.6.2 (F-Droid)?

### ISSUE THREAD

**Issue by calllib** [abrensch/brouter#376]
There is a new version 1.6.2 on F-Droid, about 4x as large as the previous. However, the change log at http://brouter.de/brouter/revisions.html stops at 1.6.1. Which changes were made to 1.6.2?

**Comment by poutnikl** [comment]
Could it be a fake version?

**Comment by afischerdev** [comment]
I'm have no idea who or what triggered this. But it seed not to be a fake version.
But it works with little outdated sources. 

May be @zod could started it with this [question](https://github.com/abrensch/brouter/issues/178#issuecomment-974691478)?    -- Seems to work ;-)

Anyway, what I see we could/should do:
- investigate what triggers F-Droid
- discuss and fix if the current version it the one we like to see online
- update BRouter to 1.6.3 and generate a release tag where F-Droid can work on
- trigger F-Droid again
- for the update of [BRouter page](http://brouter.de/brouter/revisions.html) we need the help of @abrensch to sign the update with same key as old 1.6.1 and transfer new version to this page.

What do you think?

**Comment by zod** [comment]
It seems this was triggered by this [commit](https://gitlab.com/fdroid/fdroiddata/-/commit/52bf374ab37598045ab47e48479f1de8edda3b04) which updated the [BRouter metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/btools.routingapp.yml) in the F-Droid repository.

This builds some intermediate [commit](https://github.com/abrensch/brouter/tree/12116b846787dd9fb030257fe6de90b39c0e6f71) because F-Droid watches the BRouter repository for changes and this was the first commit with a new version number.

The F-Droid metadata for BRouter seems a bit strange, because it lists individual commits and versions for each sub-project of BRouter and also has patches to individual pom files (which should no longer be used).

Going forward we should publish tags and F-Droid should only build those tags.

**Comment by afischerdev** [comment]
@zod 
Seems to be the reason. And yes, the switch to tags would be great.

But also a long time from 7. Oct.

@calllib 
I think the way to Android 11 brings us the bigger size.

**Comment by linsui** [comment]
I'll update the UpdateCheckMode so that only tagged versions are picked.

**Comment by afischerdev** [comment]
Great, thanks a lot.
