### ISSUE TITLE
1.6.3 API 19: Destruction of the old Brouter data folder content

### ISSUE THREAD

**Issue by poutnikl** [abrensch/brouter#379]
I understand there are Android 11 related reasons ( I have A10 ) for moving data from emulated/0/Brouter to emulated/0/Android/media.

I have updated 1.6.1 API 10? to 1.6.3 API 19 version (from brouter.de releases).  I got choice for 2 locations for data folder during installation. The new media one and the old one - I have chosen the latter and got a whole bunch of error messages I tapped through so they are not handy.

What I do not understand is wiping out all valuable data in old location (custom profiles, all rd5 files) without moving them. Especially when the general update dialogue says your data will not be destroyed.

rd5 files  can be redownloaded and profiles can be obtained or generated again, but it was unfortunate surprise.

**Comment by afischerdev** [comment]
I'm sorry for that, but I can't say at the moment what is the reason. But I think it matchs [other issue](https://github.com/abrensch/brouter/issues/312#issuecomment-1001061242).

There is a migration function at [BRouterView ](https://github.com/abrensch/brouter/blob/f1b21fc270c02b61405998acafdf7e7340ddbb9c/brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java#L206) and this works for me on Android 10 with old path on /Android/data/... or /brouter/.. Data is transfered to new folder in Android/media and cleared in old folder. Only the folders are not removed.

**Comment by poutnikl** [comment]
Is possible file moving failed because destination = source, and then data from old ( =new too ) location were deleted? Folders remained, some empty (I guess), so ecwith 1 or few version empty files (like 1.6.x,  0 bytes)

**Comment by afischerdev** [comment]
That could be the reason. This situation is not checked. It clears the folders but newer copies a file.

What do you think and all others, should we **make an update**?

I guess it belongs to 
`android:preserveLegacyExternalStorage="true"`
I haven't tested migration on all constallation after this is added.

**Comment by zod** [comment]
I don't think this is caused by `android:preserveLegacyExternalStorage="true"`. This settings just allows the app to keep its existing write permissions when doing an upgrade. This allows writing to locations which were available when targeting < Android Q.

Your added check now disables writing to locations which android allows access to. Is this intended?

**Comment by afischerdev** [comment]
@zod 
No, I've changed this, please see last commit.

**Comment by afischerdev** [comment]
@zod 
> I don't think this is caused by `android:preserveLegacyExternalStorage="true"`. This settings just allows the app to keep its existing write permissions when doing an upgrade. This allows writing to locations which were available when targeting < Android Q.

I only said that I didn't enough testing after it was added. ;-(

**Comment by zod** [comment]
TBH I don't really get the idea of some parts of those commits

https://github.com/abrensch/brouter/blob/15e84c81ea23408abde8605bd57a87a777003ce2/brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java#L599-L602

There was no check for a specific android version because our API19 build allows accessing external storage on Android10+. With this check it's no longer possible to select a basedir in legacy storage.

Is it intentional to disallow using legacy storage with API19?

https://github.com/abrensch/brouter/blob/15e84c81ea23408abde8605bd57a87a777003ce2/brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java#L127-L134

It seems `startSetup` is called with an old basedir. In which case should this be used?

**Comment by afischerdev** [comment]
@zod 
>There was no check for a specific android version because our API19 build allows accessing external storage on Android10+. With this check it's no longer possible to select a basedir in legacy storage.

Api19 version will still work, but on Api30 version this enables access to folders in main folder when it has write access before. E.g. update from Api28 to Api30 version.

> It seems startSetup is called with an old basedir. In which case should this be used?

When we re use an 'old' basedir in main folder on Android10 then the check a line above brings always a dialog for migration. We don't use any preferences so I thought it would be an idea to check the version file.
And other option was to set the check above to Android R, but I like the 'early' migration to media folder.
Or, another way, we send all users - who don't want to migrate - to the Api19 version. But this is only available on BRouter.de in last brouter zip.
So, what to do?

**Comment by zod** [comment]
> @zod
> 
> > There was no check for a specific android version because our API19 build allows accessing external storage on Android10+. With this check it's no longer possible to select a basedir in legacy storage.
> 
> Api19 version will still work, but on Api30 version this enables access to folders in main folder when it has write access before. E.g. update from Api28 to Api30 version.

Installing API19 build with those changes on Android 11 doesn't allow selecting a `/storage/emulated/0` which was still possible in BRouter 1.6.3. I think this check is wrong because even on Android 11 it would be possible to use this path with the API19 build.

> > It seems startSetup is called with an old basedir. In which case should this be used?
> 
> When we re use an 'old' basedir in main folder on Android10 then the check a line above brings always a dialog for migration. We don't use any preferences so I thought it would be an idea to check the version file. And other option was to set the check above to Android R, but I like the 'early' migration to media folder. Or, another way, we send all users - who don't want to migrate - to the Api19 version.

I think it's best to suggest the migration starting with Android Q but also all versions above. Migration should not be required since for upgrades it's still possible to access _legacy storage_ even on Android R.

> But this is only available on BRouter.de in last brouter zip. So, what to do?
- Remove the check version in https://github.com/abrensch/brouter/blob/15e84c81ea23408abde8605bd57a87a777003ce2/brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java#L599-L602
- Change the check in https://github.com/abrensch/brouter/blob/15e84c81ea23408abde8605bd57a87a777003ce2/brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java#L127-L134 to `android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q`

**Comment by afischerdev** [comment]
@zod 
Ok for me - without testing. But could you do that. I have not the time the next days. Thanks.
