### ISSUE TITLE
Car routing issue

### ISSUE THREAD

**Issue by Tiemichael** [abrensch/brouter#407]
First of all let me thank you for providing this great project!

For the last several years I am doing quite a detailed planning of my holidays, which are a mixture of walking and driving by car.
I am using Brouter-Web as well as a local server installation on my PC. 

When trying to reach a specific  car-park I get the message '_Error: cannot find a route for given points. Maybe try to move them closer to roads?_' - although both start- and end-point are on a road or car-park. 
Looking a little deeper, the routing stops when the road is switched to "motor_vehicle | designated". 

Routing engines like Graphhopper or Google don't have issues.
I wonder why my access to this road is blocked, and how I can change the 'car-eco' profile to make it accessible.
[Here the brouter-web link for the route](https://brouter.de/brouter-web/#map=19/43.30758/-5.05149/standard&lonlats=-5.052123,43.30745;-5.050449,43.307649&profile=car-eco)
[Here the link to the suspected place in OSM](https://www.openstreetmap.org/way/94842389#map=16/43.3075/-5.0502)

Not sure if this the right place to ask, but nevertheless I would be grateful for help!

**Comment by Tiemichael** [comment]
Sorry for my 'to early' post, 
but I was able to solve issue which was caused by the 'barrier'

**Comment by polyscias** [comment]
Yes, caused by https://www.openstreetmap.org/node/1101007291 and https://www.openstreetmap.org/node/1101006322. These nodes are missing an appropriate access= tag.

I am a bit surprised these are not marked by [brouter suspects for Spain](https://brouter.de/brouter/suspects/Spain/all). (Coordinates are -5,05, 43,3077), is that because of highway=tertiary?
