### ISSUE TITLE
invalid response

### ISSUE THREAD

**Issue by HarelM** [abrensch/brouter#42]
Hi,
First of all great project!
When running the following request the response returns with only one value in coordinates:
http://h2096617.stratoserver.net:443/brouter?nogos=&alternativeidx=0&format=geojson&profile=trekking&lonlats=34.7094,30.5926|34.7107,30.5928
is it working as designed or a bug?

Thanks,
Harel M.

**Comment by abrensch** [comment]
A bug. Affected are all strcutures where 2 ways make up a loop without a third exit. Here's another example:

http://brouter.de/brouter-web/#zoom=18&lat=49.735875&lon=8.57316&layer=OpenStreetMap&nogos=34.711089,30.588864,186&alternativeidx=0&format=geojson&lonlats=8.573359,49.73622|8.573917,49.736501&profile=trekking

Routing through such structures is never a problem, only if the endpoint is inside the loop.

The logic is really messed up at this point, because routing happens in a network with "trivial nodes" supressed, and the "final segment" is identified by it's 2 non-trivial nodes, so if that gets ambigious, things go wrong.

Thanks for reporting, even if there  will probably not be a fix.

**Comment by zstadler** [comment]
I'm afraid I didn't understand the answer. 

Given the example above, it seems like there is no way of telling Brouter to go through the road north of Alte Schule. Right!? 

Also, the route produced by Brouter seems to be broken:

http://brouter.de/brouter-web/#zoom=19&lat=49.73629&lon=8.573484&layer=OpenStreetMap&nogos=34.711089,30.588864,186&alternativeidx=0&format=geojson&lonlats=8.573359,49.73622|8.573904,49.73651|8.574604,49.73622&profile=trekking

**Comment by abrensch** [comment]
>> it seems like there is no way of telling Brouter to go through the road north of Alte Schule. Right!?

using a nogo-area on the secondary road or a profile strongly avoiding secondaries will route you north of Alte Schule. The problem really occurs only if the endpoint is within such a loop. Or an immedaite point (which is the endpoint of a routing section), this is why your additional example is broken.

**Comment by zstadler** [comment]
Thanks for the prompt response!

In my humble opinion, both workarounds are not in-line with what may be consider as an essential requirement from a routing algorithm: find a route between [every] two points, assuming a legal route exists.

Creating a no-go area or tuning the profile to effectively do the same would require knowledge and analysis of the topology - something the user would expect from the algorithm, and not vice-versa. 

Please consider tuning the brouter algorithm to find the complete route n such cases.

Thanks in advance,
Zeev

**Comment by quaelnix** [comment]
@afischerdev, this has been fixed by now, right?

**Comment by afischerdev** [comment]
@quaelnix 
Interesting question. I can't say, the samples all looking alright and no idea what they was looking before.
[start sample](http://brouter.de/brouter-web/#map=18/30.59304/34.71058/standard&lonlats=34.7094,30.5926;34.7107,30.5928)

@HarelM @zstadler 
Please don't hesitate to open this again if you're still having trouble.

**Comment by HarelM** [comment]
We have moved to use graphhopper and are very satisfied with it. Good luck with this project!
