### ISSUE TITLE
new data files?

### ISSUE THREAD

**Issue by jotpe** [abrensch/brouter#49]
Currently the [data files](http://brouter.de/brouter/segments3/) are showing the 30th of October. Wasn't there a weekly update?

**Comment by abrensch** [comment]
The new data-files are in a "segments4" folder: http://brouter.de/brouter/segments4/

This is due to the version update, 1.2 -> 1.3.2, which includes a file-format-change that is not upward-compatibe (but downwards).

I leave the old data files in the "segments3" folder for some time, but do not update them anymore.

The new files, used by the current revision of BRouter (1.3.2) are much smaller and do not require carsubset-files anymore.
