### ISSUE TITLE
How to generate estimated_traffic_class data

### ISSUE THREAD

**Issue by FFMbyBicycle** [abrensch/brouter#496]
Together with @mjaschen I tried to find a way to generate the "estimated_traffic_class" data from scratch. The estimations are working fine for me and I'm missing them at bikerouter.de :wink: At the moment I have to decide if I use the traffic data at brouter.de or if I will be able to send a Link to someone with my profile.

So far we found out that there is a [car-traffic_analysis.brf](https://github.com/abrensch/brouter/blob/master/misc/scripts/mapcreation/process_pbf_planet.sh#L68-L80) which seems to be used for this and calls a [special case](https://github.com/abrensch/brouter/blob/master/brouter-server/src/main/java/btools/server/BRouter.java#L90-L109) using "seed" keyword. This generates some data at a "traffic" subdirectory. This works for me but I have no idea what we have to do with the generated .trf files.

There seems to be a [traffic_simulation.sh](https://github.com/abrensch/brouter/blob/master/misc/scripts/mapcreation/process_pbf_planet_production.sh#L39) outside of this repository, maybe this does the magic? Or am I missing a step somewhere?

I can offer some Linux/scripting knowledge, time and will to write some documentation.

**Comment by polyscias** [comment]
The estimated_traffic_class is generated by the [estimated_traffic_class function](https://github.com/abrensch/brouter/blob/d081e5eb18476c4c7a79bafde0c8ce9d442c4bd1/brouter-map-creator/src/main/java/btools/mapcreator/OsmTrafficMap.java#L191) and underlying code.

It is not clear to me how this code is working but I think that with enough time you can find out what it is doing. Documenting that would be great.

**Comment by quaelnix** [comment]
@polyscias, Arndt once described it here (though in German): https://forum.openstreetmap.org/viewtopic.php?id=31044

**Comment by polyscias** [comment]
Okay, I did put the text [through deepl](https://www.deepl.com/translator?share=generic#de/en/%0A%0AHab's%20jetzt%20doch%20mal%20geschafft%2C%20einen%20ersten%20Wurf%20%20f%C3%BCr%20Verkehrs-Fluss-Sch%C3%A4tzungen%20in%20BRouter%20zu%20implementieren.%20Das%20ist%20das%20Thema%2C%20was%20ich%20in%20dem%20Lightning%20Talk%20auf%20der%20FOSSGIS%20in%20M%C3%BCnster%20kurz%20diskutiert%20hatte%20(%202.%20Talk%20ab%20ca.%20Minute%206%20in%20https%3A%5C%2F%5C%2Fyoutu.be%5C%2F_dtnHn71Ejk%3Flist%3DPLTli%20%E2%80%A6%20Uzh_0v6Z6T%20)%0A%0AGeht%20also%20darum%2C%20ein%20Pseudo-Tag%20f%C3%BCr%20die%20gesch%C3%A4tzte%20Verkehrsbelastung%20einer%20Strasse%20aus%20dem%20Strassennetz%20selbst%20zu%20generieren.%20Dazu%20nehme%20ich%20das%20einfache%20Modell%2C%20dass%20alle%20Leute%20von%20zuhause%20auf%20dem%20k%C3%BCrzesten%20Weg%20zur%20Autobahn%20und%20zu%C3%BCrck%20fahren%20wollen%2C%20summiere%20den%20Verkehr%20entsprechend%20auf%20und%20schreibe%20ab%20einer%20gewissen%20Schwelle%20die%20Summe%20als%20Pseudo-Tag%20an%20den%20Weg.%0A%0ADie%20Fl%C3%A4che%20wird%20also%2C%20ausgehend%20von%20den%20Autobahnanschlusspunkten%2C%20baumf%C3%B6rmig%20erschlossen.%20Optisch%20dargestellt%20f%C3%BCr%20den%20S%C3%BCd-West-Quadranten%20Deutschland%20hier%3A%20http%3A%5C%2F%5C%2Fbrouter.de%5C%2Fbrouter_bin%5C%2Ftraffic_E5_N45.png%20Zu%20jedem%205x5%20Grad%20Quadranten%20wird%201%20Grad%20Rand%20mitberechnet%20f%C3%BCr%20das%20Strassennetzt%20und%205%20Grad%20Rand%20f%C3%BCr%20das%20Autobahnnetz%2C%20um%20keine%20Artefakte%20an%20den%20Kachelr%C3%A4ndern%20zu%20bekommen.%0A%0ADie%20Verkehrssumme%20dr%C3%BCckt%20grob%20gesagt%20aus%2C%20wieviel%20Meter%20Wohnstrasse%20(oder%20%3C%3D%20Tempo50%20Strasse)%20eine%20Strasse%20versorgt%2C%20wobei%20diese%20Versorgungsbeziehung%20noch%20entfernungsabh%C3%A4ngig%20untersr%C3%BCckt%20wird%20mit%2020km%20L%C3%A4ngenskala.%20%20) and the idea is clear to me.

I am not so sure it is a good way to get the "estimated traffic load" is there within a city more traffic on the roads getting to the highway entrance/exit? I think it is better to use the [OSM highway qualification](https://wiki.openstreetmap.org/wiki/Key:highway) (primary/secondary/tertiary/unclassified/residential) and maybe the maxspeed to get a "estimated traffic load"

In Dutch context, a busy road (with >=50 km/h speed limits) is often chosen for bicycle routing because there will be cycle paths alone that road.

**Comment by FFMbyBicycle** [comment]
Thanks for your hints! The system is not perfect, but working quite good in my opinion.

I didn't want to start a discussion about other implementations, but get it working for bikerouter / other instances. Currently you get different results using the same profile depending on which brouter-web instance you're using and that's a little bit confusing. Sadly I'm not a software engineer and can't reverse-engineer the final segment data provided by Arndt.

**Comment by quaelnix** [comment]
> This works for me but I have no idea what we have to do with the generated .trf files.

Looking at the code, I would say that these .trf files are ingested automatically by the `addTrafficClass` function:

https://github.com/abrensch/brouter/blob/a764c788ba17158c4e7d4decdeb2ecd2a659bd4d/brouter-map-creator/src/main/java/btools/mapcreator/WayLinker.java#L156

https://github.com/abrensch/brouter/blob/a764c788ba17158c4e7d4decdeb2ecd2a659bd4d/brouter-map-creator/src/main/java/btools/mapcreator/WayLinker.java#L217

https://github.com/abrensch/brouter/blob/a764c788ba17158c4e7d4decdeb2ecd2a659bd4d/brouter-map-creator/src/main/java/btools/mapcreator/WayLinker.java#L268-L272

https://github.com/abrensch/brouter/blob/a764c788ba17158c4e7d4decdeb2ecd2a659bd4d/brouter-map-creator/src/main/java/btools/mapcreator/WayLinker.java#L487

https://github.com/abrensch/brouter/blob/9662e50a438b9aeb13a4dc9f4e890ddf48df949b/brouter-map-creator/src/main/java/btools/mapcreator/OsmNodeP.java#L94-L97

https://github.com/abrensch/brouter/blob/9662e50a438b9aeb13a4dc9f4e890ddf48df949b/brouter-map-creator/src/main/java/btools/mapcreator/OsmNodeP.java#L213-L217

**Comment by EssBee59** [comment]
Hello,

Thank for the documentation above!
I wasa interested to discover the jobs and could generate the RD5's with the "estimated_traffic_class" tag by following the steps decribed...but I think, there is an error somewhere...

Assuming the generation is done in the "root" directory mapcreation,  then we have these commands:
cd tmp
mkdir traffic
then start the seek jobs to generate the trf files in mapcreation/tmp/traffic

Anf then start the "waylinker" to add the tags:
But on my local test system, waylinker is looking for trf files in mapcreation/traffic, NOT in mappcresation/tmp/traffic !

After moving the traffic directory to mapcreation, the tags were added properly

**Comment by quaelnix** [comment]
The `estimated_traffic_class` data is now generated as part of the new pseudo tag generation.

Preliminary documentation: https://github.com/abrensch/brouter/blob/master/misc/scripts/mapcreation/readme_database.md
