### ISSUE TITLE
oneway:bicycle

### ISSUE THREAD

**Issue by jotpe** [abrensch/brouter#51]
Bicycle ways having a `oneway:bicycle` and a missing `oneway` are not treated as oneways.

For example here the direct route against the oneway:bicycle should not be taken, it would be better to route on the opposite cycle path:
http://brouter.de/brouter-web/#zoom=16&lat=50.93419&lon=6.97131&layer=OpenStreetMap&lonlats=6.971506,50.936621|6.971871,50.931478&nogos=&alternativeidx=0&format=geojson&profile=trekking

This assign statement should correct that.

```
assign oneway =
       if oneway=yes|true|1 then true
       else if oneway:bicycle=yes then true
       else if oneway= then junction=roundabout else false
```

**Comment by abrensch** [comment]
Thanks, I will incliude that in the next update.

There's another issue with cycleway-directions: sometimes both sides are not onway-tagged in any way, but it's assumed to take the "correct" side anyway. In these cases, the mapping direction is an indication of what the correct side is, so maybe introducing a *small* assymetry according to the mapping direction can solve that.

On the other hand, for explictly tagged situations, the assymetry shouldn't be a drastic one, but also rather small?

**Comment by jotpe** [comment]
Good idea.
Setting ```onewaypenalty``` to 0.15 in case of ```reversedirection=yes``` only, gives good results to me.

**Comment by uboot212a** [comment]
I can't find the change in the trekking.brf and the brouter-app version 1.4.2 uses the wrong bikelane at the left side of the street. Is the change included in the coming version? Thanks for the good work.

**Comment by uboot212a** [comment]
I've testet the bad behavior with the newest version 1.4.5 and the behavior is unchanged. With the online version I found out, that the `badoneway` is not assigned for `oneway:bicycle=yes` lanes. Changing the folowing part changed the behavior in that way, that a so tagged bikelane is only used for short distances (pushing the bike).
```
assign badoneway =
    if reversedirection=yes then
        if oneway:bicycle=yes then true=
        else if oneway= then junction=roundabout=
        else oneway=yes|true|1=
    else oneway=-1
```

A good example: http://brouter.de/brouter-web/#zoom=18&lat=48.154624&lon=11.552424&layer=OpenStreetMap&lonlats=11.553867,48.154066|11.552339,48.155222&nogos=&alternativeidx=0&format=geojson
With the above described change you have to push your bike some meters and change the side of the street two times riding the bike instead of pushing it the whole way.

**Comment by abrensch** [comment]
I added oneway:bicycle=yes to version 1.4.7

however, not yet the reversedirection=yes only penalty, need more testing

**Comment by abrensch** [comment]
done for 1.4.7
