### ISSUE TITLE
more detailed height model

### ISSUE THREAD

**Issue by ghost** [abrensch/brouter#56]
ClusterGIS has released a 15m/px global height model under CCBY
http://www.theearthsrelief.com/

Maybe its worth thinking about using it.

**Comment by buma** [comment]
This seems great. But the problem is that downloads are hillshaded reliefs. Which can be used to create web or paper maps. But it would be harder to get heights out of them. Not impossible but hard IMHO. You could gt some height from colors but since it is hillshaded one side of the mountain is different color then the other but height is the same. SRTM is height data which can be used to create hillshade and get elevation information.
