### ISSUE TITLE
separate concrete and concrete:plates / concrete:lanes

### ISSUE THREAD

**Issue by utack** [abrensch/brouter#61]
Hi,

The lookup seems to mash concrete, concrete:plates and concrete:lanes into one single thing
`surface;0000212587 concrete concrete:plates concrete:lanes
`
It would be nice to have these separated, because concrete is pretty smooth and nice to bike on, while the plates and lanes are a major pain and slow down roadbikes significantly

Thanks for consideration

**Comment by abrensch** [comment]
I could'nt change the aliasing, because that would have triggered regressions for existing profiles.

What I did for 1.4.9 is to add the tag "concrete", which is seldom used in the osm database, and added a pre-processor hack to add concrete=xxx for surface=concrete:xxx

So you should have now a way to acces sthe information you need
