### ISSUE TITLE
Dual carriageway and left turn

### ISSUE THREAD

**Issue by r11d11** [abrensch/brouter#625]
Hello,
one small issue with Brouter offline and profile car.
When I had to turn left on a dual carriageway Cruiser (which uses Brouter offline) says I have to go straight and wenn I have reached the central reservation of the street it says I have to go left. These two commands come within milliseconds and you have no chance to turn left if you only look at the the arrow top left.
When you drive only with voice instructions you are complete lost.

I would like it better if Brouter would suppress the first indication straight ahead when Brouter notices that you have to turn left 20 metres further on.

An example:
[2Lanes and left turn.zip](https://github.com/abrensch/brouter/files/12565335/2Lanes.and.left.turn.zip)

Cruiser_left_turn

![turn_left_corr](https://github.com/abrensch/brouter/assets/101214119/30ebcdff-9e3d-4e3f-99f5-f4642389b7cb)

**Comment by Ciutnik** [comment]
Hi. When using Cruiser, I also noticed a problem with turning left onto a dual carriageway. The problem is different, because it involves the lack of left turn instructions:

<img src="https://github.com/abrensch/brouter/assets/122647782/648feef7-2f55-4cb4-9f94-e6d8e70b8530" width="50%"/>

This is exactly where it is on the BRouter website: [Left turn](https://brouter.de/brouter-web/#map=18/52.22868/21.08535/standard&lonlats=21.085318,52.228593;21.086476,52.22807&profile=car-eco)

And by the way, huge words of appreciation to the creators of BRouter! This is the first time I have the opportunity to thank you for your great work. Thanks!

**Comment by afischerdev** [comment]
Thanks for your samples.
If you don't mind I will move this samples to issue #613. There already is already a place for this kind of problems.
