### ISSUE TITLE
OruxMaps turn instructions no longer working

### ISSUE THREAD

**Issue by quaelnix** [abrensch/brouter#673]
Forward from [mtb-news.de](https://www.mtb-news.de/forum/t/bikerouter-de-brouter-web-fragen-antworten-hilfe-profile-tipps-etc.917910/page-67#post-19226975):
> Somehow I no longer get turn-by-turn instructions in OruxMaps (7.4.27), neither visually on the route nor as an announcement (which was possible before). It doesn't matter whether I calculate the route directly in OruxMaps via the BRouter app or whether I import a GPX file from Bikerouter.de. For the latter, I had already set the "turnInstructionMode" to "oruxmaps-style" in the options.

Used software versions:

- OruxMaps v7.4.27
- BRouter v1.7.3

**Comment by quaelnix** [comment]
It apparently does not work regardless of whether the `turnInstructionMode` is set to `oruxmaps-style` or not.

**Comment by vodie** [comment]
On Android OruxMaps calls BRouter via service interface with turn instructions in Locus Maps style and convert them internally. Since the Locus Maps turn instructions are changed, they no longer work with OruxMaps.
The OruxMaps style was created by me for brouter-web to get turn instructions in the exported file. This was done after OruxMaps developed the turn instruction import on Android.

To solve the problem OruxMaps has to change their import via Service Interface on Android.

**Comment by afischerdev** [comment]
I can confirm, with an edited profile it will work.

@vodie 
The easiest way could be to switch the parameter `turnInstructionFormat` in the interface call.
I tested with this in BRouter app to get your favorite result:
```
      params.remove("turnInstructionFormat");
      params.putInt("timode", 6);
```
Please have a look at the interface [definition](https://github.com/abrensch/brouter/blob/master/brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl). May be you like to change some other things that are new in the interface.
And there are some new [voice hints](https://github.com/abrensch/brouter/blob/47ee77bc35c3e9ae97c387a342c55f80c4624d13/brouter-core/src/main/java/btools/router/VoiceHint.java#L12) that are not included in your export.
Please let us know when you need some changes in voice hint export.

**Comment by afischerdev** [comment]
@rkflx 
> The latter is caused by either OruxMaps not keeping up or by BRouter unnecessarily breaking backward compatibility by changing the old format instead of introducing a new format.

Yes, that is the point. 
But please keep in mind the OruxMaps v7.4.27 is from 1. January 2017 and someone has to change the app (Locus or OruxMaps), in this case OruxMaps because the change was related to Locus export.
OruxMaps was informed about the changes and has already updated the Play Store version - I think.

**Comment by vodie** [comment]
@afischerdev
I am not involved in OruxMaps. I did only the OruxMaps export on BRouter to help someone from velombilforum.de.

**Comment by oruxman** [comment]
Hello everyone!

Tomorrow I will release the free Oruxmaps version 7.4.28 which will fix this issue.

The fault was OruxMaps, which was using a mode intended for another app.

Sorry for the problems caused!


orux

**Comment by afischerdev** [comment]
a new OruxMaps version 7.4.28 is available.

@oruxman 
Thank you
