### ISSUE TITLE
bug in hight model at bridges

### ISSUE THREAD

**Issue by MasiMaster** [abrensch/brouter#70]
If a waypoint is set on a bridge, the height model of the complete route shows an error. Example:
http://brouter.de/brouter-web/#zoom=17&lat=50.936377&lon=6.96419&layer=OpenStreetMap&lonlats=6.961185,50.935677|6.965976,50.936269|6.970396,50.936397&nogos=&profile=trekking&alternativeidx=0&format=geojson
If the bridge-waypoint is deleted, the height model mostly went to ok.

**Comment by abrensch** [comment]
I see.

Elevation on bridges and tunnels is set to VOID by the preprocessor. During routing, elevation of the last node with non-void elevation is repeated for the bridge/tunnel section.

Processing with wayspoints is technically individual routig for indivual sections, so that repetition does not work, and you get VOID elevation in the middle of the track.

Could add some logic to fill the voids after routing is done... I leave the issue open for that

**Comment by hugobqd** [comment]
BRouter is awesome, please correct this issue !

**Comment by Phyks** [comment]
Hi, this should have been fixed in BRouter-web side in https://github.com/nrenner/brouter-web/issues/147. See https://github.com/abrensch/brouter/issues/137#issuecomment-497462644 as well for more infos on these missing elevations.
